name: Upload artifacts

on:
  release:
    types: [created]

jobs:
  upload-artifacts:
    name: Upload artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]
    steps:
      - name: Check repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --no-progress --non-interactive

      - name: Setup git config
        run: |
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${REPOSITORY}

      - name: Package VSCode extension into ".vsix" file
        run: yarn vsce:package

      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: './$ASSET_NAME'
          asset_name: $ASSET_NAME
          asset_content_type: application/vsix
        env:
          ASSET_NAME: '${{ github.event.repository.name }}-${GITHUB_REF#refs/*/}.vsix'

    env:
      USER_NAME: 'github-actions[bot]'
      USER_EMAIL: 'github-actions[bot]@users.noreply.github.com'
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} #GITHUB_TOKEN is required for `release-it`
      REPOSITORY: ${{ github.repository }}
